version: '3.4'

services: 

    hotels:
        image: hotelsbookingkata-hotels-infrastructure-boot:latest
        ports:
            - "32000:8080"
    company:
        image: hotelsbookingkata-company-infrastructure-boot:latest
        ports: 
            - "32001:8080"
    book:
        image: hotelsbookingkata-book-infrastructure-boot:latest
        ports:
            - "32002:8080"
        depends_on:
            - hotels
            - company
            