---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: hotels
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
      - name: hotels
        image: opengeekv2/hotels:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: hotels
---
apiVersion: v1
kind: Service
metadata:
  name: hotels
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32001
  selector:
    app: hotels